apiVersion: v2
name: external-secrets
version: 0.1.0
description: Installs External Secrets Operator and Platform-managed ClusterSecretStores.
type: application
appVersion: "v2.9.0"

dependencies:
  - name: external-secrets
    version: 2.9.0
    repository: https://charts.external-secrets.io
