{{- $service := .Values.public.readiness.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}-readiness
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- toYaml $service.selectorLabels | nindent 4 }}
    gateway.envoyproxy.io/owning-gateway-name: {{ .Values.public.gateway.name | quote }}
    gateway.envoyproxy.io/owning-gateway-namespace: {{ .Release.Namespace | quote }}
  ports:
    - name: {{ $service.portName | quote }}
      port: {{ $service.port }}
      protocol: TCP
      targetPort: {{ $service.targetPort | quote }}
