extends: default

ignore:
  - "**/.github/**"
  - "**/.terraform/**"
  - "**/templates/**"

rules:
  empty-values: enable
  comments:
    require-starting-space: true
    min-spaces-from-content: 1
  comments-indentation:
    level: error
  document-start: false
  empty-lines:
    max: 1
  line-length: disable
  truthy:
    check-keys: false
