{{- range $name, $spec := .Values.clusterSecretStores }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: "{{ $name }}"
  labels:
    {{- include "platform-external-secrets.labels" $ | nindent 4 }}
spec:
  {{- toYaml $spec | nindent 2 }}
{{- end }}
