#!/usr/bin/env bash
set -e

CLUSTER_NAME="platform"

if kind get clusters | grep -q "$CLUSTER_NAME"; then
    echo "Kind cluster: $CLUSTER_NAME already exists. Skipping creation."
else
    echo "Creating kind cluster: $CLUSTER_NAME"
    kind create cluster --config kind-config.yaml --name $CLUSTER_NAME
    kubectl config use-context kind-$CLUSTER_NAME
fi
